[versions]
agp = "9.0.0"
library = "8.13.2"
kotlin.android = "2.3.0

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android.library = { id = "com.android.library", version.ref = "library" }
jetbrains.kotlin.android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin.android" }

